### ISSUE TITLE
tinydns import tool not populating default SOA values if unspecified

### ISSUE THREAD

**Issue by ispcolohost** [msimerson/NicTool#127]
I've run into an issue where if the tinydns import utility imports a zone where the SOA values have not been explicitly defined, such as:

Zdomain.com:ns1.domain.com:hostmaster.domain.com::::::

In tinydns world, this SOA record would result in the tinydns defaults for serial, refresh, retry, expire, and min being served.  Those values are the modification time of the data file, 16384 seconds, 2048 seconds, 1048576 seconds, and 2560 seconds.

Nictool will successfully set a serial number based on the current date, but leaves the rest blank.  This results in the BIND export, and other modules that utilize BIND-format exports (such as Dyn API-based export) producing invalid data that fails to import because the constructed file looks like:

$ORIGIN domain.com.
domain.com.          IN      SOA         hostmaster.domain.com. (
                                        2016072705    ; serial
                                           ; refresh
                                             ; retry
                                            ; expiry
                                           ; minimum
                                        )

**Comment by msimerson** [comment]
Hmmm, that's an interesting problem.

Since tinydns was the first NicTool import/export format, it was likely that the exports would also be in tinydns format. Thus it was desirable to import them as they were discovered, such that the import/export cycle resulted in an export that looked just like the import.

That's less of a good choice now that multiple exports are available. I think that the imports should be altered such that export format defaults are made explicit during the imports. That way, your data can be imported and then published consistently to any DNS server or service.

A Pull Request implementing this is welcome.
