### ISSUE TITLE
import/Base.pm lowercasing rdata

### ISSUE THREAD

**Issue by ispcolohost** [msimerson/NicTool#135]
Hello, I'm curious if there was a particular reason to lc the resource record data; from import/Base.pm:

```
my %request = (
    nt_zone_id => $p{zone_id},
    name       => lc $p{name},
    address    => ($p{type} eq 'NAPTR' ? $p{address} : lc $p{address}),
    type       => $p{type},
);
```

I simply removed the lc in my copy of nictool, but I'm worried there may have been a reason for that which I've overlooked.

The reason I removed it is because it is lowercasing TXT records, and DKIM data, for example, is case-sensitive.

**Comment by msimerson** [comment]
The primary reason is duplicate suppression in the raw data like this:

````
name   IN TXT  "I want a puppy"
name   IN TXT  "i want a puppy"

name   IN AAAA "2607:f060:b008:feed::2"
name   IN AAAA "2607:f060:B008:FEED::2"

@   IN  MX "mail.example.com."
@   IN  MX "mAil.example.com."
````

I'm paraphrasing, but RFC 2181 basically says that records with identical name, type, ttl, and address are not permitted. In DNS terms, those records are duplicates and should not be permitted. Since NicToolServer is case sensitive (as it must be), it permits those duplicate records to be entered. Thus it is best to catch them during import.

In retrospect, the lower casing needs some improvement. The following record types should be excluded from lower casing:

- A
- NAPTR (#89)
- TXT (arguably: "yes for SPF, no for DKIM, ..")

The following RR types should also be evaluated for `lc` exclusion as well: SIG, KEY, SSHPF, LOC, RRSIG, DNSKEY, NSEC3PARAM, TSIG.
