### ISSUE TITLE
non-numeric chars in port: 'issue' at NicToolServer/Export.pm line 866.

### ISSUE THREAD

**Issue by Popyllol** [msimerson/NicTool#202]
### NicTool version
2.34
### perl version
This is perl 5, version 18, subversion 2 (v5.18.2) built for x86_64-linux-gnu-thread-multi
### OS version
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty
### Expected behavior
Export should contain:
.	86400	IN	CAA	0 issue "letsencrypt.org"
### Observed behavior
Export comtains:
.	86400	IN	CAA	0 0 "letsencrypt.org"
### Steps to reproduce
I use PowerDNS export and there might be a bug with the new CAA records.
When I run the export:
#  su -m ${EXPORT_USER} -c "/var/www/nictool/server/bin/nt_export.pl -nsid 31 -force -pfextra"
I get:
nsid 31 has 9 zones, 0 changed, forced, retrieved 9 zonesnon-numeric chars in port: 'issue' at /usr/local/share/perl/5.18.2/NicToolServer/Export.pm line 866.
...

Your code (sub is_ip_port in NicToolServer/Export.pm line 866 for version 2.34) looks for an integer where 'issue' comes in the field.
Thanks,
   Lars

**Comment by msimerson** [comment]
I don't see how that's possible. The PowerDNS exporter uses the BIND class as it's parent and [that code](https://github.com/msimerson/NicTool/blob/master/server/lib/NicToolServer/Export/BIND.pm#L462-L470) doesn't try to validate the tag.

**Comment by BSG2000** [comment]
We have the same problem here. Do you see a possibility to create valid entries for example fixing the bind class?

**Comment by BSG2000** [comment]
@msimerson A colleague looked at the code and thinks that the solution is somewhere else:

`my $crit = $self->{nte}->is_ip_port( $r->{weight} );`
[L464-L465 in BIND.pm](https://github.com/msimerson/NicTool/blob/master/server/lib/NicToolServer/Export/BIND.pm#L464-L465)

`is_ip_port in` [L872-L887 in Export.pm](https://github.com/msimerson/NicTool/blob/master/server/lib/NicToolServer/Export.pm#L872-L887)

There, the entry to be exported is validated. In line 881, the entry is rejected because it is not an integer value. So it should be enough to add another check if the value is not an integer, but a CAA entry according to [RFC 6844](https://tools.ietf.org/html/rfc6844).

**Comment by msimerson** [comment]
Are you guys running a "release" version of NicTool?   An issue very much like this was resolved already in #193.

**Comment by BSG2000** [comment]
We're running Version 2.34 and will first update to an actual release. Thank you for support, I will give you an feedback...

**Comment by msimerson** [comment]
2.34 is the latest release, but newer code is in this repo already.

**Comment by Popyllol** [comment]
We can close this bug. The git version fixed the issue.
