### ISSUE TITLE
Even more granular rights?

### ISSUE THREAD

**Issue by rduffner** [msimerson/NicTool#208]
Hi,

my co-worker wrote a Go-program that talks to the ACME-server and to NicTool (to solve the Let's Encrypt DNS-Challenge). As such, it needs to create DNS records.

With my version (2.31, will update soon) I found that if a user has "create"+"delete", he still can't create records. He will also need "Edit".

Ideally, for this use-case (and maybe for others) would be a permission set that allows to create records and delete them - and only allow to delete records that this specific user has previously created.
And no editing of other records.

It just bothers me to give this nictool-user so much power ;-)

**Comment by msimerson** [comment]
I'm going from memory, but there's no way to accomplish this currently. You can create records as one user and delegate them to another, so that a delegate can edit them, but creating records is a **zone** permission, as is **deleting** records. Either a user can create and delete a record in a zone, or they can't.

**Comment by rduffner** [comment]
Sure. Not a real "issue".

I just like to run a tight ship.

But if you ever revamp the permission-system, maybe give this a thought.
