### ISSUE TITLE
Failed to change password

### ISSUE THREAD

**Issue by moetiker** [msimerson/NicTool#214]
NicTool version:  2.34
perl version:  5.22.1
OS version: Ubuntu 16.04
Expected behavior: 

Password change works.

Observed behavior: 

the system throughs an error:

ModPerl::ROOT::ModPerl::Registry::usr_local_nictool_client_htdocs_user_2ecgi:/usr/local/nictool/client/htdocs/user.cgi:412 at /usr/local/nictool/client/lib/NicToolClient.pm line 1317.
Client error: 508: FATAL: pkcs_5_alg2 process failed: Invalid keysize for block cipher. at /usr/local/lib/x86_64-linux-gnu/perl/5.22.1/Crypt/KeyDerivation.pm line 28.

Steps to reproduce:

Select an existing user and change the password.

**Comment by msimerson** [comment]
Looks like CryptX isn't [fully] installed correctly. Try reinstalling it.

**Comment by r4nd0m123** [comment]
This is the same as the issue I reported earlier - #195 

@moetiker I encountered this error when I left the 'Current Password' field empty, but if you enter in any value it will reset the password.

@msimerson is this page not expecting a null value in the 'Current Password' field?

**Comment by msimerson** [comment]
Ahh, knowing you are using an empty password for the current is helpful information. It used to be that NicTool required the old password in order to set a new one. Some time since that restriction was relaxed if the currently logged in user has administrator privileges. There's likely a code path that needs updating.

**Comment by msimerson** [comment]
This issue appears to be fixed in #241
