### ISSUE TITLE
NicTool allows adding both TXT and CNAME for the same record

### ISSUE THREAD

**Issue by rainerduffner** [msimerson/NicTool#236]
### NicTool version
2.34
### perl version
5.24
### OS version
11.1-RELEASE-p8
### Expected behavior
NicTool allows adding both TXT and CNAME for the same record
### Observed behavior
NicTool should refuse to allow adding "special" records for entries that already exist
### Steps to reproduce
create "bla" record as txt, then add "blu" record as CNAME

This may be related to #189 ?

**Comment by he32** [comment]
There is some code in `server/lib/NicToolServer/Zone/Record/Sanity.pm`, specifically, `_valid_cname()` which I thought was supposed to catch instances such as this.
However, I've not verified that `name_collisions()` returns all the records which should be checked,
which would be necessary...

Also, I admit I don't know in which cases `_valid_cname()` (and the invoking
`new_or_edit_basic_verify`) are called.

**Comment by he32** [comment]
Hmm, with nictool version 2.34, I'm unable to reproduce this; if I add a TXT record and subsequently try to add a CNAME record with the same name, I get an error saying `record foobar already exists within zone as an (TXT) record: RFC 1034, 2181, & 4035`.

However, the presence of NS or SOA records, as at the zone apex, does not appear to prevent the creation of a CNAME at the zone apex, which is an all too common error/misunderstanding.

**Comment by he32** [comment]
A test for "CNAME at zone apex" can be found at (I hope this is portable...)
https://github.com/msimerson/NicTool/commit/a89f171982ee186c8d721df5790efa41a3f50d76
This is however un-tested, and as indicated above, the test will probably fail, since no code
change to check for zone apex is present.  I suspect SOA and NS records are "special" in the database, and don't appear as "normal zone records", and that this is the cause of that particular problem, and that `_valid_cname()` needs to explicitly test for attempted "zone apex" placement.

**Comment by msimerson** [comment]
I cannot reproduce either, see screenshot. My recommendation is to install the latest NicTool from git and be sure to 'make install' it so that's the version Apache is loading.

NicTool does permit CNAMEs at the apex, coincident with NS records. That's technically a RFC violation, but it's also [a common use case](https://serverfault.com/questions/613829/why-cant-a-cname-record-be-used-at-the-apex-aka-root-of-a-domain) and it's an inadvertent feature I've used for nigh 20 years. Enough that I recently pestered a particular NS vendor into relaxing their restriction on its use, and they are doing so.

<img width="645" alt="Screen Shot 2020-01-16 at 10 19 14 PM" src="https://user-images.githubusercontent.com/261635/72588810-4e755a00-38ae-11ea-9fa8-ebe9cfe22c09.png">

If you still have this issue after confirming that you're running the latest NicTool, we can reopen this issue.

**Comment by he32** [comment]
Um, allowing "CNAME at the apex" is not just "technically" an RFC violation -- it is a serious mistake to allow it, since it violates everything about the semantics of the CNAME record.

If you use BIND as the DNS name server behind NicTool, it will refuse to load a zone with a CNAME at the apex where both the SOA and NS records live.  You *CANNOT* have a CNAME record registered on a label which has other records registered on it.

**Comment by msimerson** [comment]
I understand your argument, but a) yes I can (and do) have a CNAME at the apex, and b) it works exactly my clients wants it to. It would be better if a DNAME was able to do the job but it doesn't.  We may have to agree that reasonable people can disagree about this.

**Comment by he32** [comment]
I think I understand where the desire for 'CNAME at the apex' is coming from.  However, it is a mistake.  I predict that the current apparent lenient treatment of such a mis-configuration by recursive resolvers is going to be treated the same way EDNS non-compliance was treated in the 2019 DNS "flag day", ref. https://dnsflagday.net/2019/ (although that apparently won't happen in 2020).  I am holding some hope that https://tools.ietf.org/html/draft-ietf-dnsop-svcb-httpssvc-01 will see adoption, which aims to tackle this particular problem.

**Comment by rainerduffner** [comment]
BIND will not load these zones, last time I checked.
But people want to have it nevertheless (when they have stuff on AWS and want to create a CNAME for it, including at the apex).

Maybe I'm just particularly gullible for simply believing in the RFCs?
;-)

**Comment by msimerson** [comment]
It's not a matter of simple believes, it's more a matter of careful reading the RFCs. It's very easy to read a SHOULD and think MUST.

**Comment by he32** [comment]
You may believe CNAME can be combined with other RR types.
My claim is that in general you can't and at the same time claim to
follow the IETF DNS standards -- the sole exception is a few DNSSEC
RR types.

I'll just refer to https://tools.ietf.org/html/rfc2181#section-10
which is pretty clearly in favor of my claim that CNAME at zone apex 
is in violation of the IETF DNS standards.

That some providers choose either directly or via private non-standard
extensions to offer similar functionality doesn't really change the facts
wrt. CNAME and IETF standards conformance.
